# Generated by Django 6.1 on 2026-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('category', models.CharField(choices=[('PRODUCTIVITY_HABITS', 'Productivity & Habits'), ('MINDSET_THINKING', 'Mindset & Thinking'), ('PERSONAL_FINANCE', 'Personal Finance'), ('BUSINESS_LEADERSHIP', 'Business & Leadership'), ('MOTIVATION_MENTAL_TOUGHNESS', 'Motivation & Mental Toughness'), ('SPIRITUALITY_MINDFULNESS', 'Spirituality & Mindfulness'), ('HEALTH_SCIENCE', 'Health & Science'), ('RELATIONSHIPS', 'Relationships')], default='PRODUCTIVITY_HABITS', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['available_copies'],
            },
        ),
    ]
